Repository w3c/webrtc-stats, pull requests merged in 2020-03, with the labels that each got.

#535 Add counters for bytes sent by ICE pings (#534)
  webrtc-stats.html
Labels: Submitter input needed

#551 RTCSctpTransportStats additional stats
  webrtc-stats.html
Labels: Editors can integrate

#557 Adapt references to dictionary member existence
  webrtc-stats.html
  webrtc-stats.js
Labels: Editorial
