Repository w3c/webrtc-stats, pull requests merged in 2022-09, with the labels that each got.

#669 Only expose RTCCodecStats objects currently in use
  webrtc-stats.html
Labels: Editors can integrate

#682 Add RTCAudioPlayoutStats, synthesizedSamplesDuration and totalSamplesDuration
  webrtc-stats.html
Labels: Editors can integrate

#683 Add totalPlayoutDelay and totalSamplesCount to RTCAudioPlayoutStats.
  webrtc-stats.html
Labels: Editors can integrate

#685 Add totalCaptureDelay and totalSamplesCaptured to RTCAudioSourceStats.
  webrtc-stats.html
Labels: Editors can integrate

#693 Add media-playout to summary table
  webrtc-stats.html
Labels: Editorial

#670 Add powerEfficient[En/De]coder (#666) and fingerprint mitigations (#675).
  webrtc-stats.html
Labels: needs test
